'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace ec.gob.sri.celcer.recepcionPruebas
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="RecepcionComprobantesOfflineServiceSoapBinding", [Namespace]:="http://ec.gob.sri.ws.recepcion"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(mensaje())),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(comprobante()))>  _
    Partial Public Class RecepcionComprobantesOfflineService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private validarComprobanteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ClasesComprobantesElectronicos.My.MySettings.Default.ClasesComprobantesElectronicos_ec_gob_sri_celcer_recepcionPruebas_RecepcionComprobantesService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event validarComprobanteCompleted As validarComprobanteCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://ec.gob.sri.ws.recepcion", ResponseNamespace:="http://ec.gob.sri.ws.recepcion", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>
        Public Function validarComprobante(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")> ByVal xml() As Byte) As <System.Xml.Serialization.XmlElementAttribute("RespuestaRecepcionComprobante", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> Object()
            Return Me.Invoke("validarComprobante", New Object() {xml})
        End Function

        '''<remarks/>
        Public Overloads Sub validarComprobanteAsync(ByVal xml() As Byte)
            Me.validarComprobanteAsync(xml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub validarComprobanteAsync(ByVal xml() As Byte, ByVal userState As Object)
            If (Me.validarComprobanteOperationCompleted Is Nothing) Then
                Me.validarComprobanteOperationCompleted = AddressOf Me.OnvalidarComprobanteOperationCompleted
            End If
            Me.InvokeAsync("validarComprobante", New Object() {xml}, Me.validarComprobanteOperationCompleted, userState)
        End Sub
        
        Private Sub OnvalidarComprobanteOperationCompleted(ByVal arg As Object)
            If (Not (Me.validarComprobanteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent validarComprobanteCompleted(Me, New validarComprobanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ec.gob.sri.ws.recepcion")>  _
    Partial Public Class respuestaSolicitud
        
        Private estadoField As String
        
        Private comprobantesField() As comprobante
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property comprobantes() As comprobante()
            Get
                Return Me.comprobantesField
            End Get
            Set
                Me.comprobantesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ec.gob.sri.ws.recepcion")>  _
    Partial Public Class comprobante
        
        Private claveAccesoField As String
        
        Private mensajesField() As mensaje
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property claveAcceso() As String
            Get
                Return Me.claveAccesoField
            End Get
            Set
                Me.claveAccesoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property mensajes() As mensaje()
            Get
                Return Me.mensajesField
            End Get
            Set
                Me.mensajesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ec.gob.sri.ws.recepcion")>  _
    Partial Public Class mensaje
        
        Private identificadorField As String
        
        Private mensaje1Field As String
        
        Private informacionAdicionalField As String
        
        Private tipoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property identificador() As String
            Get
                Return Me.identificadorField
            End Get
            Set
                Me.identificadorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("mensaje", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje1() As String
            Get
                Return Me.mensaje1Field
            End Get
            Set
                Me.mensaje1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property informacionAdicional() As String
            Get
                Return Me.informacionAdicionalField
            End Get
            Set
                Me.informacionAdicionalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipo() As String
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub validarComprobanteCompletedEventHandler(ByVal sender As Object, ByVal e As validarComprobanteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class validarComprobanteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuestaSolicitud
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuestaSolicitud)
            End Get
        End Property
    End Class
End Namespace
